replacing edepon with ebulkcond, which can produce much more configureable outputs and now takes into account (and requires) package version to be explicitly stated, to produce the same output as edepon just use "ebulkcond <package-atom> depends"

diff --git a/etools b/etools
--- a/etools
+++ b/etools
@@ -25,10 +25,11 @@ if [[ $APPLET == "etools" ]]; then
 			}
 			dolink erepo
 			dolink eshowuse
-			dolink eshowdepon
 			dolink elistpkgs
 			dolink etsls
 			dolink eunfoldmarch
+			dolink bulkenv
+			dolink erebuild
 		;;
 		-h | --help | *)
 			echo -e "usage:\n  $APPLET: Symlink this script to \"erepo\", \"eshowuse\", or any of the other applets inside of it to utilize them.\n  $(n=1; while [[ $n -lt $(basename $0 | wc -c) ]]; do printf " "; n=$((n+1)); done)  or run \"$APPLET -i <path/to/link/to>\" to automatically symlink every applet to a specified directory.\n"
@@ -84,14 +85,6 @@ elif [[ $APPLET == "erepo" ]]; then
 elif [[ $APPLET == "eshowuse" ]]; then
 	if [[ ! "$1" ]]; then >&2 echo -e "usage:\n  $APPLET <use-flag>\n" && exit 1; fi
 	for pkg in $(equery -q hasuse "$1"); do echo $pkg: $(equery -q uses $pkg | grep "$1"); done
-elif [[ $APPLET == "edepon" ]]; then
-	if test -z "$(ls "/var/db/repos/"*"/$@" 2> /dev/null)"; then >&2 echo "$APPLET: package \"$@\" does not exist." && exit 1; fi
-	while read -r line; do
-		if test -n "$(echo $line | grep -o "\-r[0-9]")"; then line="$(echo $line|rev|cut -d'-' -f2-|rev)"; fi
-		line="$(echo $line|rev|cut -d'-' -f2-|rev)"
-		output="$output $line"
-	done < <(equery depends "$@"|cut -d'=' -f2)
-	echo $output
 elif [[ $APPLET == "elistpkgs" ]]; then
 	case $3 in
 		"")	
@@ -192,4 +185,43 @@ elif [[ $APPLET == "eunfoldmarch" ]]; then
 		output="$output $line"
 	done < <(echo "$output_tmp")
 	echo $output
+elif [[ $APPLET == "ebulkcond" ]]; then
+	case "$1" in
+		-h|--help|"")
+			echo "$APPLET: \"<category>/<package>-<version>\" <[depends|depgraph]> (config <text-to-append>)"
+			exit 0
+		;;
+	esac
+	package="$1" && packagename="$package"
+	if test -n "$(echo $packagename| grep -o "\-r[0-9]")"; then packagename="$(echo $packagename|rev|cut -d'-' -f2-|rev)"; fi
+	packagename="$(echo $packagename|rev|cut -d'-' -f2-|rev)"
+	if test -z "$(ls "/var/db/repos/"*"/$packagename/${package##*/}.ebuild" 2> /dev/null)"; then >&2 echo "$APPLET: package \"$package\" does not exist." && exit 1; fi
+	if [ ! "$package" ]; then echo "Please provide a package atom!" && exit 1; fi
+	case "$2" in
+		depends|d|depgraph|g)
+			condition="$2"
+			case "$condition" in
+				depends|d)
+					input="$(equery $condition "$package")"
+				;;
+				depgraph|g)
+					input="$(equery $condition "$package"|cut -d' ' -f6-|tail -n +2)"
+				;;
+			esac
+		;;
+		*)
+			echo "Invalid condition"
+			exit 1
+		;;
+	esac
+	while read -r line; do
+		if test -n "$(echo $line | grep -o "\-r[0-9]")"; then line="$(echo $line|rev|cut -d'-' -f2-|rev)"; fi
+		line="$(echo $line|rev|cut -d'-' -f2-|rev)"
+		if [[ "$3" == "config" ]]; then
+			output="$output\n$line ${@:4}"
+		else
+			output="$output $line"
+		fi
+	done < <(echo "$input"|cut -d'=' -f2)
+	echo -e $output
 fi
